# Generated by Django 3.1.7 on 2021-03-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210319_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('pinCode', models.PositiveIntegerField(max_length=6)),
                ('state', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('HouseName', models.CharField(max_length=150)),
                ('landMark', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
            ],
        ),
    ]
