# Generated by Django 3.1.7 on 2021-03-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_profile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='Gender',
        ),
    ]
