# Generated by Django 3.1.7 on 2021-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210327_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='prof_Image',
            field=models.ImageField(null=True, upload_to='profpic/'),
        ),
    ]
