# Generated by Django 3.1.7 on 2021-04-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_person_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
