# Generated by Django 3.1.7 on 2021-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210402_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Welcome_coupan',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
