# Generated by Django 3.1.7 on 2021-04-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210406_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Welcome_coupan',
        ),
    ]
