# Generated by Django 3.1.7 on 2021-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_person_welcome_coupan'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Welcome_coupan',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
