# Generated by Django 3.1.7 on 2021-04-07 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210407_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Welcome_coupan',
        ),
    ]
