# Generated by Django 3.1.7 on 2021-03-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_desc', models.TextField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('M_image', models.ImageField(upload_to='')),
                ('s_image', models.ImageField(upload_to='')),
                ('main_image', models.ImageField(upload_to='')),
                ('p_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.add_category')),
            ],
        ),
    ]
