# Generated by Django 3.1.7 on 2021-03-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='M_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='main_image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='s_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
