# Generated by Django 3.1.7 on 2021-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_auto_20210318_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_category',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
